services:
  docker-cron:
    image: ghcr.io/cplieger/docker-cron:latest@sha256:2e1f11801c62d04c6908712b74aa5353c72dadb1488a2a4ab28f43123d32c323
    container_name: docker-cron
    restart: unless-stopped
    user: "0:0"  # required for docker socket access

    environment:
      TZ: "Europe/Paris"
      SCHEDULE_1: "0 2 * * *"
      COMMAND_1: "docker exec my-db pg_dump -U postgres mydb > /backups/mydb.sql"
      TIMEOUT_1: "3600"
      SCHEDULE_2: "0 4 * * 0"
      COMMAND_2: "docker exec my-app find /tmp -mtime +7 -delete"
      TIMEOUT_2: "300"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/run/locks:/run/locks"
